name: Deploy Cloud Functions

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Deploy Cloud Function
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: make deploy USEROUTPUT=false
